# vim: set filetype=sh:
# user-mode TTYs without any realizers
user_tty "vc1-tty"
user_tty "vc2-tty"
user_tty "vc3-tty"
service_with_dedicated_logger "terminal-emulator@vc1"
service_with_dedicated_logger "terminal-emulator@vc2"
service_with_dedicated_logger "terminal-emulator@vc3"
login_service_with_dedicated_logger "vc1-tty"
login_service_with_dedicated_logger "vc2-tty"
login_service_with_dedicated_logger "vc3-tty"
service_with_dedicated_logger "console-input-method@head0"
service_with_dedicated_logger "console-multiplexor@head0"

# kernel TTYs
kvt_login_service_with_dedicated_logger "1"
kvt_login_service_with_dedicated_logger "2"
kvt_login_service_with_dedicated_logger "3"
kvt_login_service_with_dedicated_logger "4"
kvt_login_service_with_dedicated_logger "5"
kvt_login_service_with_dedicated_logger "6"
kvt_login_service_with_dedicated_logger "7"
kvt_login_service_with_dedicated_logger "8"
kvt_login_service_with_dedicated_logger "9"
kvt_login_service_with_dedicated_logger "10"
kvt_login_service_with_dedicated_logger "11"
kvt_login_service_with_dedicated_logger "12"
service_with_dedicated_logger "ttylogin-starter"

# HID support (including passthrough realizers)
service_with_dedicated_logger "kernel-vt-loadkeys"
service_with_dedicated_logger "kernel-vt-setfont"
service_with_dedicated_logger "kernel-vt-setterm"
service_with_dedicated_logger "kernel-vt-kbdrate"
fan_in_logger "console-evdev-realizer"
fan_in_logger "console-fb-realizer"
fan_in_logger "console-ps2-mouse-realizer"
