# vim: set filetype=sh:
# user-mode TTYs without any realizers
user_tty "vc1-tty"
user_tty "vc2-tty"
user_tty "vc3-tty"
service_with_dedicated_logger "terminal-emulator@vc1"
service_with_dedicated_logger "terminal-emulator@vc2"
service_with_dedicated_logger "terminal-emulator@vc3"
login_service_with_dedicated_logger "vc1-tty"
login_service_with_dedicated_logger "vc2-tty"
login_service_with_dedicated_logger "vc3-tty"
service_with_dedicated_logger "console-input-method@head0"
service_with_dedicated_logger "console-multiplexor@head0"
serial_tty_callout_service_with_dedicated_logger "0"

# kernel TTYs
kvt_login_service_with_dedicated_logger "0"
kvt_login_service_with_dedicated_logger "1"
kvt_login_service_with_dedicated_logger "2"
kvt_login_service_with_dedicated_logger "3"
kvt_login_service_with_dedicated_logger "4"
kvt_login_service_with_dedicated_logger "5"
kvt_login_service_with_dedicated_logger "6"
kvt_login_service_with_dedicated_logger "7"
kvt_login_service_with_dedicated_logger "8"
kvt_login_service_with_dedicated_logger "9"
kvt_login_service_with_dedicated_logger "a"
kvt_login_service_with_dedicated_logger "b"
kvt_login_service_with_dedicated_logger "c"
kvt_login_service_with_dedicated_logger "d"
kvt_login_service_with_dedicated_logger "e"
kvt_login_service_with_dedicated_logger "f"

# HID support (including passthrough realizers)
service_with_dedicated_logger "kernel-vt-kbdcontrol"
service_with_dedicated_logger "kernel-vt-vidcontrol"
fan_in_logger "console-pcat-kbd-realizer"
fan_in_logger "console-pcat-mouse-realizer"
fan_in_logger "console-ugen-hid-realizer"
fan_in_logger "console-uhid-realizer"
fan_in_logger "console-evdev-realizer"
fan_in_logger "console-wscons-realizer"
fan_in_logger "uhidd"
fan_in_logger "moused"
